//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCafe.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoreanStudyCafeEntities : DbContext
    {
        public KoreanStudyCafeEntities()
            : base("name=KoreanStudyCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceLine> InvoiceLines { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Locker> Lockers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<StudyRoom> StudyRooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
