// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WindowsFormsApp1ML.Model
{
    public class ModelInput
    {
        [ColumnName("MachineLearningTempID"), LoadColumn(0)]
        public float MachineLearningTempID { get; set; }


        [ColumnName("BeverageID"), LoadColumn(1)]
        public float BeverageID { get; set; }


        [ColumnName("DayQuater"), LoadColumn(2)]
        public string DayQuater { get; set; }


        [ColumnName("Usage"), LoadColumn(3)]
        public float Usage { get; set; }


        [ColumnName("UserCount"), LoadColumn(4)]
        public float UserCount { get; set; }


        [ColumnName("DayOfTheWeek"), LoadColumn(5)]
        public string DayOfTheWeek { get; set; }


    }
}
